baseurl = "https://ameliabarber.netlify.com/"
title = "Amelia E. Barber"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "UA-144248073-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
toc = false
customCSS = ["css/tables.css"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/header.jpeg"
  SEOTitle = "Amelia E. Barber"
  description = "Website of Amelia E. Barber, PhD"
  keyword = "microbial genomics, fungal biology, antifungal resistance, genomics, computational biology"
  slogan = "Genomics & Resistance of Fungal Pathogens"

  image_404 = "img/me.jpeg"
  title_404 = ""

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Wet lab-trained scientist %>% data science and computational biology."
  sidebar_avatar = "img/me.jpeg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 0 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = false
  email          = "amelia.barber@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/frau_dr_barber"
  linkedin       = "https://www.linkedin.com/in/barberae/"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/ameliabedelia"
  #wechat         = "your wechat qr code image"
#  medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  
  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "About me"
  href =  "/top/about/"
  [[params.addtional_menus]]
  title =  "Vitae"
  href =  "/top/vitae/"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
