---
title: "Vitae"
author: "Amelia"
date: 2019-07-20
tags: ["cv"]
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Curriculum Vitae

*last updated: December 1, 2021*

My complete CV can be found [here](/top/vitae_files/CV.pdf)\

[Education](#Education)<br>
[Positions](#Positions)<br>
[Research Support](#Support)<br>
[Awards](#Awards)<br>
[Publications](#Publications)<br>



## Amelia E. Barber<br>
Email: amelia.barber[at]leibniz-hki.de<br>


### Education {#Education}
PhD, **University of Utah** (2016)<br>
Microbiology and Immunology<br>
+ *Zebrafish reveal variable effects of Escherichia coli during sepsis*<br>
+ Advisor: Matthew Mulvey

BS, **University of Wisconin-Madison** (2006)<br>
Medical Microbiology and Immunology, Women's Studies

### Positions

**Junior Group Leader** (September 2020-present)<br>
Leibniz Institute for Natural Product Research and Infection Biology -  Hans Knöll Institute. Jena, Germany.<br>

**Postdoctoral Fellow** (2016-2020)<br>
Leibniz Institute for Natural Product Research and Infection Biology -  Hans Knöll Institute. Jena, Germany.<br>
Institute of Hygiene and Microbiology, University of Würzburg. Würzburg, Germany.<br>
+ Research group of Oliver Kurzai

**PhD Candidate** (2010-2016)<br>
University of Utah, Department of Pathology. Salt Lake City, UT.<br>
+ Research group of Matthew Mulvey

**Research Specialist** (2007-2009)<br>
University of Wisconsin-Madison, Department of Neurology. Madison, WI.<br>
+ Research group of Clive Svendsen

**Undergraduate Laboratory Assistant** (2005-2007)<br>
University of Wisconsin-Madison, Department of Entomology. Madison, WI.<br>
+ Research group of Ken Raffa

**Undergraduate Research Assistant** (2004-2005)<br>
University of Wisconsin-Madison, School of Nursing. Madison, WI.<br>
+ Research group of Barbara St. Pierre Schneider


### Reseach Support {#Support}

**2020-24**. DfG Excellence Cluster Balance of the Microverse Junior Research Group <br>
**2012-2014**. NIAID T-32 Microbial Pathogenesis Training Grant <br>

### Awards {#Awards}


**2021-22**. Leibniz Mentoring Program<br>
**2021**. Medac Research Prize <br>
**2018**. International Society for Human and Animal Mycology Attendance Grant <br>
**2017**. European Confederation of Medical Mycology Young Investigators Travel Award <br>
**2015**. ASM Richard and Mary Finkelstein Travel Award <br>
**2015**. University of Utah Graduate School Travel Award <br>

### Publications {#Publications}

**Preprints & Submitted Manuscripts**<br>

*None at present*<br>

**Accepted Manuscripts**<br>

**Barber AE**, Sae-Ong T, Kang K, Seelbinder B, Li J, Walther G, Panagiotou G, Kurzai O. *Aspergillus fumigatus* pan-genome analysis identifies genetic variants associated with human infection. 2021. *Nature Microbiology*.<br>
<https://doi.org/10.1038/s41564-021-00993-x>

**Barber AE**, Riedel J, Sae-Ong T, Kang K, Brabetz W, Panagiotou G, Deising HB, Kurzai O. Effects of agricultural fungicide use on *Aspergillus fumigatus* abundance, antifungal susceptibility, and population structure. 2020. *mBio*.<br>
<https://doi.org/10.1128/mBio.02213-20>

**Barber AE**, Scheufen S, Walther G, Kurzai O, Schmidt V. Low Rate of Azole Resistance in Cases of Avian Aspergillosis in Germany. 2020. *Medical Mycology*.<br> <https://doi.org/10.1093/mmy/myaa045>

Hamprecht A, **Barber AE**, Mellinghoff SC, Thelen P, Walther G, Yu Y, Neurgaonkar P, Dandekar T, Cornely OA, Martin R, Kurzai O. Occurence of Candida auris in Germany is linked to prior exposure to foreign healthcare. 2019. *Emerging Infectious Diseases*. Sept;25(9).<br> <https://doi.org/10.3201/eid2509.190262>

**Barber AE**, Weber M, Kaerger K, Goelz H, Walther G, Linde J, Duerschmidt D, Markert A, Guthke R, Kurzai O. Comparative genomics of serial Candida glabrata isolates and the rapid acquisition of echinocandin resistance during therapy. 2019. *Antimicrobial Agents & Chemotherapy*. Jan;63(2).<br>
<https://doi.org/10.1128/AAC.01628-18>

Kjelstrüp CK, **Barber AE**, Norton JP, Mulvey MA, L’Abee-Lund TM. Escherichia coli O78 isolated from septicemic lambs shows high pathogenicity in a zebrafish model. 2017. *Veterinary Research*. Jan;48(1):3.<br>
<https://doi.org/10.1186/s13567-016-0407-0>

**Barber AE**, Fleming BA, Mulvey MA. Similarly Lethal Strains of Extraintestinal Pathogenic Escherichia coli Trigger Markedly Diverse Host Responses in a Zebrafish Model of Sepsis. 2016. *mSphere*. Apr;1(2).<br>
**Featured on Episode 126 of the ASM Podcast “This Week in Microbiology”**<br>
<https://doi.org/10.1128/mSphere.00062-16>  

**Barber AE**, Norton JP, Wiles TJ, Mulvey MA. Strengths and Limitations of Model Systems for the Study of Urinary Tract Infections. Microbiology and Molecular Biology Reviews. 2016. *Microbiology and Molecular Biology Reviews*. Mar;80(2):351-67.<br>
<https://doi.org/10.1128/MMBR.00067-15>

**Barber AE**, Norton JP, Spivak AM, Mulvey MA. Urinary Tract Infections: Current and Emerging Management Strategies. 2013. *Clinical Infectious Diseases*. Sept;57(5):719-24.<br>
<https://doi.org/10.1093/cid/cit284>

Debnath I., Norton JP, **Barber AE**, Ott EM, Dhakal BK, Kulesus RR, Mulvey MA. The Cpx Stress Response System Potentiates the Fitness and Virulence of Uropathogenic Escherichia coli. 2013. *Infection & Immunity*. May;81(5):1450-9.<br>
<https://doi.org/10.1128/IAI.01213-12>

Ebert AD, **Barber AE**, Heins BM, Svendsen CN. Ex vivo Delivery of GDNF Maintains Motor Function and Prevents Neuronal Loss in a Transgenic Mouse Model of Huntington’s disease. 2010. *Experimental Neurology*. Jul;224(1):155-62.<br>
<https://doi.org/10.1016/j.expneurol.2010.03.005>

Ebert AD, Beres AJ, **Barber AE**, Svendsen CN. Human Neural Progenitor Cells Over-expressing IGF-1 Protect Dopamine Neurons and Restore Function in a Rat Model of Parkinson's Disease. 2008. *Experimental Neurology*. Jan;209(1):213-223.<br>
<https://doi.org/10.1016/j.expneurol.2007.09.022>

